[Snake]
; default movement keybinds (AWSD)
MoveUp=W
MoveDown=S
MoveLeft=A
MoveRight=D
; alternative movement keybinds (arrow keys)
AltMoveUp=Up
AltMoveDown=Down
AltMoveLeft=Left
AltMoveRight=Right

[General]
TogglePause=Escape
; Restart=R